
version: '3.2'

services:
  eidasbridge:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: eidasbridge-dev.ebsi.zyz
    ports:
      - '9000:9000'
    environment:
      - FLASK_ENV=development
    volumes:
      - ./:/code
    networks: 
      - backend

  hubserver:
    build: 
        context: ./demo
        dockerfile: ./Dockerfile
    image: hubserver-dev.ebsi.zyz
    ports:
      - '9001:9001'
    environment:
      - FLASK_ENV=development
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"