
version: '3.2'

services:
  eidasbridge:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: eidasbridge-dev.ebsi.zyz
    ports:
      - '5002:5002'
    environment:
      - FLASK_ENV=development
    volumes:
      - ./:/code
    depends_on: 
      - hubserver

  hubserver:
    build: 
        context: ./demo
        dockerfile: ./Dockerfile
    image: hubserver-dev.ebsi.zyz
    ports:
      - '9092:9092'
    environment:
      - FLASK_ENV=development