
version: '3.7'

services:
  eidasbridge:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: "${DOCKER_EIDASBRIDGE_IMAGE_NAME}:${TAG}"
    container_name: "${DOCKER_EIDASBRIDGE_CONTAINER_NAME}"
    restart: always
    ports:
      - '9000:9000'
    env_file:
      - .env
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '50'
    volumes:
      - ./:/code
    networks: 
      - backend

  hubserver:
    build: 
        context: ./demo
        dockerfile: ./Dockerfile
    image: "${DOCKER_HUBSERVER_IMAGE_NAME}:${TAG}"
    container_name: "${DOCKER_HUBSERVER_CONTAINER_NAME}"
    restart: always
    logging:
      options:
        max-size: '100m'
        max-file: '50'
    ports:
      - '9001:9001'
    env_file:
      - .env
    restart: always
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"